  // Get the value in localStorage. JSON.parse() converts string in value
  let score = JSON.parse(localStorage.getItem('score')) || { 
    playerWin:0,
    computerWin:0,
    tie:0,
  }
      
  let choice='';


  
  function pickComputerMove(){
    let result='';
    let randomNumber = Math.random();
    if (randomNumber>=0 && randomNumber <=1/3){
      result='rock'
    }
    else if (randomNumber>1/3 && randomNumber<=2/3){
      result='paper'
    }
    else if (randomNumber >2/3 && randomNumber<=1){
      result='scissors'
    }
    return result;
    };

  function playGame(choice){ // determine the result if you win, lose or tie. then localStorage.setItem()
    const result = pickComputerMove(); // get the return value from pickComputerMove().
    if (choice ==='rock'){
      if (choice===result){
       finResult = 'Tie';
      }
      else if (result==='paper'){
       finResult = 'You lose';
      }
      else if (result==='scissors'){
       finResult = 'You win';
       
      }
    }
    else if (choice ==='scissors'){
      if (choice===result){
        finResult = 'Tie';
      }
      else if (result==='rock'){
        finResult = 'You lose';
      }
      else if (result==='paper'){
        finResult = 'You win'
      }
    }
    
    else if (choice ==='paper'){
      if (choice===result){
       finResult = 'Tie';
      }
      else if (result==='scissors'){
       finResult = 'You lose';
      }
      else if (result==='rock'){
       finResult = 'You win';
      }
    }      
    if (finResult === 'You win') {
        score.playerWin += 1;
      } 
    else if (finResult === 'You lose') {
        score.computerWin += 1;
      }
    else if (finResult === 'Tie'){
        score.tie +=1;
    }

    localStorage.setItem('score', JSON.stringify(score)); //It can only put string in localStorage, so convert the value in string using JSON.stringify().

    document.querySelector('.gameResult').innerHTML = (`You
    <img src="img/${choice}-Emoji.png" class="move-icon">
    <img src="img/${result}-Emoji.png" class="move-icon">
    Computer
    <p>
    Win: ${score.playerWin} Lose: ${score.computerWin} Tie:${score.tie}`);
  }

  function resetText(){
    document.querySelector('.gameResult').innerHTML = (`Win: ${score.playerWin} Lose: ${score.computerWin} Tie:${score.tie}`)
   };

let isAutoPlaying = false;
let intervalId;

  function autoPlay(){
    const text = document.querySelector('.auto-play-button');
    if (!isAutoPlaying){
      text.innerText = 'Stop Playing'
      intervalId = setInterval(() => {
        const playerMove = pickComputerMove();
        playGame(playerMove);
      },500);
      
      isAutoPlaying = true;

    } else {
      clearInterval(intervalId);
      isAutoPlaying = false;
      text.innerText = 'Auto Play'
    }
   }

   document.querySelector('.auto-play-button')
   .addEventListener('click',()=>{
    autoPlay();
   })
    

   document.querySelector('.js-rock-button')  
   .addEventListener('click', ()=>{    // addEventListner('click', playGame('rock')) - this does not work. playGame('rock') will return `undefined`. Instead, create a narrow function that contains PlayGame('rock')
    playGame('rock');
   })

   document.querySelector('.js-paper-button')
   .addEventListener('click',()=>{
    playGame('paper');
   })

   document.querySelector('.js-scissors-button')
   .addEventListener('click', ()=>{
    playGame('scissors');
   })


  // parameter vs argument
  // (x)=>{}; x is a parameter; playGame('rock') -- 'rock' is an argument; 

   document.addEventListener('keydown', (event)=>{  //This tells the browser to call the `playGameByKeydown` function 
    console.log(event);                             // -whenever a 'keydown' event happens on the document.
    if (event.key === 'r'){                         //When a key is pressed, a 'keydown' object is generated by the browser.
      playGame('rock');                             //The browser calls the playGameByKeydown function 
    }                                               // -and passes the event object to it as an argument.
    else if (event.key === 'p'){
      playGame('paper');
    }
    else if (event.key === 's'){
      playGame('scissors');
    }
    else if (event.key === 'a'){
      autoPlay();
    }
    else if (event.key === 'Backspace'){
      resetScore();
    }
   }) 

   let confirmHTML = '';
   function resetScore(){
    const html = `
    <p>Are you sure you want to reset the score? </p>
    <button class='confirm-yes'>Yes</button>
    <button class='confirm-no'>No</button>
    `
    confirmHTML += html

    let confirmMessage = document.querySelector('.confirm');
    confirmMessage.innerHTML = confirmHTML;

    document.querySelector('.confirm-yes').addEventListener('click',()=>{
      score.playerWin=0;
      score.computerWin=0;
      score.tie=0;
      localStorage.removeItem('score')
      resetText();
      confirmHTML = ''; confirmMessage.innerHTML = '';
    })
    document.querySelector('.confirm-no').addEventListener('click',()=>{
      confirmHTML = ''; confirmMessage.innerHTML = '';
    })
   }

   document.querySelector('.reset-score-button')
    .addEventListener('click',()=>{
      resetScore();
    })

  

